name             'postfix_test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
chef_version     '>= 16.0'
issues_url       'https://github.com/osuosl-cookbooks/osl-postfix/issues'
source_url       'https://github.com/osuosl-cookbooks/osl-postfix'
description      'Test fixture for osl-postfix resources'
version          '0.1.0'

depends          'osl-postfix'
depends          'certificate'
