---
verifier:
  name: inspec
attributes:
  boulder:
    host_aliases:
      - smtp.snowdrift.coop
      - www.smtp.snowdrift.coop
    acme:
      endpoint: http://127.0.0.1:4000
suites:
  - name: default
    run_list:
      - recipe[osl-postfix::default]
    excludes:
      - debian-8
  - name: server
    run_list:
      - recipe[osl-postfix::server]
