name             'osl-postfix'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/osl-postfix'
issues_url       'https://github.com/osuosl-cookbooks/osl-postfix/issues'
license          'Apache-2.0'
chef_version     '>= 16.0'
description      'Installs/Configures osl-postfix'
version          '3.0.0'

depends          'osl-firewall'
depends          'osl-selinux'
depends          'postfix', '~> 7.0.3'

supports         'almalinux', '~> 8.0'
supports         'almalinux', '~> 9.0'
supports         'almalinux', '~> 10.0'
supports         'debian', '~> 12.0'
supports         'debian', '~> 13.0'
supports         'ubuntu', '~> 24.04'
